name: hive_flutter
description: Extension for Hive. Makes it easier to use Hive in Flutter apps.
version: 1.0.1
homepage: https://github.com/hivedb/hive/tree/master/hive_flutter
documentation: https://docs.hivedb.dev/

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.0.4
  path_provider: ^2.0.1
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.1
  build_runner: ^2.4.4
  flutter_lints: ^2.0.1
